# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Projects
    url: project
    weight: 10
  - name: People
    url: people
    weight: 30
  - name: News & Events
    url: news_and_events
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 60
